version: '3'
services:
  ttv_db:
    container_name: ttv_db
    image: mariadb:latest
    ports:
      - "8107:3306"
    environment:
      MYSQL_DATABASE: ttv
      MYSQL_USER: ttv
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  ttv_phpmyadmin:
    container_name: ttv_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8108:80"
    environment:
      PMA_HOST: ttv_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
      UPLOAD_LIMIT: 64000M
    depends_on:
      - ttv_db

  ttv:
    container_name: ttv
    ports:
      - "8109:443"
    depends_on:
      - ttv_db
    build: .
    volumes:
      - .:/var/www/html
