<?php

/**
 * @file
 * Provides a payment entity type.
 */

use Drupal\Core\Database\Database;
use Drupal\user\UserInterface;

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function hb_payment_user_predelete(UserInterface $account) {
  // Delete payments.
  $storage = \Drupal::entityTypeManager()->getStorage('hb_payment');
  $hb_payment_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $hb_payments = $storage->loadMultiple($hb_payment_ids);
  $storage->delete($hb_payments);
}
